[project]
name = "luvatrix"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14,<3.15"
dependencies = [
  "matplotlib>=3.10.8",
  "numpy>=2.4.2",
  "pyobjc-core>=12.1",
  "pyobjc-framework-cocoa>=12.1",
  "pyobjc-framework-quartz>=12.1",
  "torch>=2.4.0",
  "vulkan>=1.3.275.1",
]
